export const dadosMock = [
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      {
        "idFuncionalidade": 3,
        "nome": "Consulta tabela de preços",
        "tbAMAPortalUsuarioFuncionalidade": []
      },
      {
        "idFuncionalidade": 2,
        "nome": "Incluir Usuário",
        "tbAMAPortalUsuarioFuncionalidade": []
      },
      {
        "idFuncionalidade": 1,
        "nome": "Gerenciar Usuários",
        "tbAMAPortalUsuarioFuncionalidade": []
      }
    ],
    "idUsuario": 1,
    "idPrestador": 205,
    "cpf": "41343494869",
    "nome": "GABRIEL PINHEIRO ",
    "celular": "11939213367",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "TECNOLOGIA DA INFORMAÇÃO",
    "admin": true,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": true,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      {
        "idFuncionalidade": 3,
        "nome": "Consulta tabela de preços",
        "tbAMAPortalUsuarioFuncionalidade": []
      }
    ],
    "idUsuario": 3326,
    "idPrestador": 205,
    "cpf": "11624258816",
    "nome": "ALBERTO EINSTEIN ",
    "celular": "11939213367",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "GLOSAS",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": true,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": true,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 3327,
    "idPrestador": 205,
    "cpf": "09498282897",
    "nome": "JOHN LOCKE",
    "celular": "11939213354",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CONTABILIDADE",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 3328,
    "idPrestador": 205,
    "cpf": "00000000000",
    "nome": "HUGO REYES",
    "celular": "11939213367",
    "senha": null,
    "email": "gabrielcampos.dgr@hotmail.com",
    "setor": "GORDINHO PERDIDO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 3329,
    "idPrestador": 205,
    "cpf": "00000000000",
    "nome": "JACK SHEPARP",
    "celular": "11933333333",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "DOUTOR CRAZY",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 3334,
    "idPrestador": 205,
    "cpf": "12345678910",
    "nome": "HANNAH PESTANA",
    "celular": "00000000000",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "COMERCIAL",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      {
        "idFuncionalidade": 2,
        "nome": "Incluir Usuário",
        "tbAMAPortalUsuarioFuncionalidade": []
      },
      {
        "idFuncionalidade": 3,
        "nome": "Consulta tabela de preços",
        "tbAMAPortalUsuarioFuncionalidade": []
      },
      {
        "idFuncionalidade": 1,
        "nome": "Gerenciar Usuários",
        "tbAMAPortalUsuarioFuncionalidade": []
      }
    ],
    "idUsuario": 3335,
    "idPrestador": 205,
    "cpf": "00000000000",
    "nome": "ALMIR SATER",
    "celular": "00000000000",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "TESTE TESTE",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": true,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 15651,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "TESTE",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 1234,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "TESTE TESTE",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 33536,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "CHIMBINHA",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 335436,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "RATO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 333796,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "LOMBARDI",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 3344636,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "CAVALO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 33165136,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "GERTRUDES",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 311336,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "SADICO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "FINANCEIRO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 635412,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 458854,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 140232,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 665412,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 123456,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
  {
    "Token": null,
    "senhaNova": null,
    "CNPJCPF": "00004286000183",
    "DadosPrestador": null,
    "Funcionalidades": [
      null
    ],
    "idUsuario": 1000,
    "idPrestador": 205,
    "cpf": "12346578910",
    "nome": "OVIDIO",
    "celular": "",
    "senha": null,
    "email": "gabrielcampos@afresp.org.br",
    "setor": "CASO",
    "admin": false,
    "senhaLiberada": true,
    "senhaPadrao": false,
    "dtInclusao": "0001-01-01T00:00:00",
    "dtCancelamento": null,
    "ativo": false,
    "tbAMAPortalUsuarioFuncionalidade": [],
    "tbCCredenciado": null
  },
]